# ASP.NET Core
# Build and test ASP.NET Core projects targeting .NET Core.
# Add steps that run tests, create a NuGet package, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/dotnet-core

trigger:
- 10_cicd_release

pool:
  vmImage: 'windows-latest'
  # name: 'MartinsXPS15'
  # demands:
  #   - agent.name -equals MARTINS_XPS15

#https://learn.microsoft.com/en-us/azure/devops/pipelines/process/stages?view=azure-devops&tabs=yaml
#stages is a logical group of jobs
#Stages run by default sequentially and you can use dependencies and conditions
variables:
  buildConfiguration: 'Release'

stages:
  - stage: runStage 
    jobs:
    - job: runAppSimple
      displayName: 'dotnet run' 
      timeoutInMinutes: 10
      steps:
        - script: dotnet run --project AppWebApiTest/AppWebApiTest.csproj
       #- bash: exit 1  #This step will now fail
  
  - stage: finalStage 
    dependsOn: 
    - buildStage 
    - runStage 
    jobs:
    - job: finalJob
      displayName: 'finalJob' 
      timeoutInMinutes: 10
      steps:
      - bash: echo "Executing finalJob"
